# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded CIG_EX10_ARP_BROADCAST 1.0 [list source [file join $dir CIG_EX10_ARP_BROADCAST.tc]]
package ifneeded CIG_EX10_ARP_PASSTHRU 1.0 [list source [file join $dir CIG_EX10_ARP_PASSTHRU.tc]]
package ifneeded CIG_EX10_DEFAULT_SNIFF 1.0 [list source [file join $dir CIG_EX10_DEFAULT_SNIFF.tc]]
package ifneeded CIG_EX10_DEFAULT_TRANSP 1.0 [list source [file join $dir CIG_EX10_DEFAULT_TRANSP.tc]]
package ifneeded CIG_EX10_IPV4VLAN_LOADBALANCE 1.0 [list source [file join $dir CIG_EX10_IPV4VLAN_LOADBALANCE.tc]]
package ifneeded CIG_EX10_IPV4_LB_BYPORT 1.0 [list source [file join $dir CIG_EX10_IPV4_LB_BYPORT.tc]]
package ifneeded CIG_EX10_IPV4_LB_ROUNDROBIN 1.0 [list source [file join $dir CIG_EX10_IPV4_LB_ROUNDROBIN.tc]]
package ifneeded CIG_EX10_IPV6VLAN_LOADBALANCE 1.0 [list source [file join $dir CIG_EX10_IPV6VLAN_LOADBALANCE.tc]]
package ifneeded CIG_EX10_IPV6_LOADBALANCE 1.0 [list source [file join $dir CIG_EX10_IPV6_LOADBALANCE.tc]]
package ifneeded CIG_EX10_IPX_DROP 1.0 [list source [file join $dir CIG_EX10_IPX_DROP.tc]]
package ifneeded CIG_EX10_IPX_PASSTHRU 1.0 [list source [file join $dir CIG_EX10_IPX_PASSTHRU.tc]]
package ifneeded CIG_EX11_PREDEFINED_ACTION_GRPS 1.0 [list source [file join $dir CIG_EX11_PREDEFINED_ACTION_GRPS.tc]]
package ifneeded CIG_EX1_SIMPLE_LB 1.0 [list source [file join $dir CIG_EX1_SIMPLE_LB.tc]]
package ifneeded CIG_EX2_SIMPLE_COPY 1.0 [list source [file join $dir CIG_EX2_SIMPLE_COPY.tc]]
package ifneeded CIG_EX3_TAP_W_LOADBALANCE 1.0 [list source [file join $dir CIG_EX3_TAP_W_LOADBALANCE.tc]]
package ifneeded CIG_EX4_TAP_W_COPY 1.0 [list source [file join $dir CIG_EX4_TAP_W_COPY.tc]]
package ifneeded CIG_EX5_COPYANDLB 1.0 [list source [file join $dir CIG_EX5_COPYANDLB.tc]]
package ifneeded CIG_EX6_TAP_W_COPYANDLB 1.0 [list source [file join $dir CIG_EX6_TAP_W_COPYANDLB.tc]]
package ifneeded CIG_EX9_IPV4LB_ARPBCAST 1.0 [list source [file join $dir CIG_EX9_IPV4LB_ARPBCAST.tc]]
package ifneeded CIG_LB_2TUPLE_ALGO 1.0 [list source [file join $dir CIG_LB_2TUPLE_ALGO.tc]]
package ifneeded CIG_LB_4TUPLE_ALGO 1.0 [list source [file join $dir CIG_LB_4TUPLE_ALGO.tc]]
package ifneeded CIG_LB_ROUNDROBIN_ALGO 1.0 [list source [file join $dir CIG_LB_ROUNDROBIN_ALGO.tc]]
package ifneeded cigprocs 1.0 [list source [file join $dir cigprocs.lib]]
