# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded CLI_CONFIG_INT_HELP 1.0 [list source [file join $dir CLI_CONFIG_INT_HELP.tc]]
package ifneeded CLI_CONFIG_SRT_HELP 1.0 [list source [file join $dir CLI_CONFIG_SRT_HELP.tc]]
package ifneeded CLI_CONFIG_STR_HELP 1.0 [list source [file join $dir CLI_CONFIG_STR_HELP.tc]]
package ifneeded CLI_CONFIG_SYS_HELP 1.0 [list source [file join $dir CLI_CONFIG_SYS_HELP.tc]]
package ifneeded CLI_CONFIG_USR_HELP 1.0 [list source [file join $dir CLI_CONFIG_USR_HELP.tc]]
package ifneeded CLI_HELP 1.0 [list source [file join $dir CLI_HELP.tc]]
package ifneeded CLI_SET 1.0 [list source [file join $dir CLI_SET.tc]]
package ifneeded CLI_SHOW 1.0 [list source [file join $dir CLI_SHOW.tc]]
