# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded BV_INSTALL_FTP 1.0 [list source [file join $dir BV_INSTALL_FTP.tc]]
package ifneeded BV_INSTALL_FTP_LDP 1.0 [list source [file join $dir BV_INSTALL_FTP_LDP.tc]]
package ifneeded BV_INSTALL_FTP_RAID 1.0 [list source [file join $dir BV_INSTALL_FTP_RAID.tc]]
package ifneeded BV_INSTALL_FTP_SFI 1.0 [list source [file join $dir BV_INSTALL_FTP_SFI.tc]]
package ifneeded BV_INSTALL_FTP_SFI_LDP 1.0 [list source [file join $dir BV_INSTALL_FTP_SFI_LDP.tc]]
package ifneeded BV_INSTALL_HTTP 1.0 [list source [file join $dir BV_INSTALL_HTTP.tc]]
package ifneeded BV_INSTALL_HTTP_LDP 1.0 [list source [file join $dir BV_INSTALL_HTTP_LDP.tc]]
package ifneeded BV_INSTALL_HTTP_SFI 1.0 [list source [file join $dir BV_INSTALL_HTTP_SFI.tc]]
package ifneeded BV_INSTALL_HTTP_SFI_LDP 1.0 [list source [file join $dir BV_INSTALL_HTTP_SFI_LDP.tc]]
package ifneeded BV_INSTALL_NFS 1.0 [list source [file join $dir BV_INSTALL_NFS.tc]]
package ifneeded BV_INSTALL_NFS_LDP 1.0 [list source [file join $dir BV_INSTALL_NFS_LDP.tc]]
package ifneeded BV_INSTALL_NFS_SFI 1.0 [list source [file join $dir BV_INSTALL_NFS_SFI.tc]]
package ifneeded BV_INSTALL_NFS_SFI_LDP 1.0 [list source [file join $dir BV_INSTALL_NFS_SFI_LDP.tc]]
package ifneeded BV_INSTALL_NO_TFTP_FTP 1.0 [list source [file join $dir BV_INSTALL_NO_TFTP_FTP.tc]]
