# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded SYS_ROUTED_ICMP_PING 1.0 [list source [file join $dir SYS_ROUTED_ICMP_PING.tc]]
package ifneeded SYS_ROUTED_TCP_FTP 1.0 [list source [file join $dir SYS_ROUTED_TCP_FTP.tc]]
package ifneeded SYS_ROUTED_TCP_SSH 1.0 [list source [file join $dir SYS_ROUTED_TCP_SSH.tc]]
package ifneeded SYS_ROUTED_TCP_TELNET 1.0 [list source [file join $dir SYS_ROUTED_TCP_TELNET.tc]]
package ifneeded SYS_TRANS_ICMP_PING 1.0 [list source [file join $dir SYS_TRANS_ICMP_PING.tc]]
package ifneeded SYS_TRANS_ICMP_PING_JUMBO 1.0 [list source [file join $dir SYS_TRANS_ICMP_PING_JUMBO.tc]]
package ifneeded SYS_TRANS_ICMP_TRACE 1.0 [list source [file join $dir SYS_TRANS_ICMP_TRACE.tc]]
package ifneeded SYS_TRANS_ICMP_TRACE_JUMBO 1.0 [list source [file join $dir SYS_TRANS_ICMP_TRACE_JUMBO.tc]]
package ifneeded SYS_TRANS_TCP_FTP 1.0 [list source [file join $dir SYS_TRANS_TCP_FTP.tc]]
package ifneeded SYS_TRANS_TCP_FTP_JUMBO 1.0 [list source [file join $dir SYS_TRANS_TCP_FTP_JUMBO.tc]]
package ifneeded SYS_TRANS_TCP_SSH 1.0 [list source [file join $dir SYS_TRANS_TCP_SSH.tc]]
package ifneeded SYS_TRANS_TCP_SSH_JUMBO 1.0 [list source [file join $dir SYS_TRANS_TCP_SSH_JUMBO.tc]]
package ifneeded SYS_TRANS_TCP_TELNET 1.0 [list source [file join $dir SYS_TRANS_TCP_TELNET.tc]]
package ifneeded SYS_TRANS_TCP_TELNET_JUMBO 1.0 [list source [file join $dir SYS_TRANS_TCP_TELNET_JUMBO.tc]]
