# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded BV_RPOWER_ALTRESET 1.0 [list source [file join $dir BV_RPOWER_ALTRESET.tc]]
package ifneeded BV_RPOWER_RESET 1.0 [list source [file join $dir BV_RPOWER_RESET.tc]]
package ifneeded BV_RPOWER_RESET_SIMPLE 1.0 [list source [file join $dir BV_RPOWER_RESET_SIMPLE.tc]]
package ifneeded LOAD_BALANCE 1.0 [list source [file join $dir LOAD_BALANCE.tc]]
