# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded CLI_SHOW_001 1.0 [list source [file join $dir CLI_SHOW_001.tc]]
package ifneeded CLI_SHOW_002 1.0 [list source [file join $dir CLI_SHOW_002.tc]]
package ifneeded DEV_TEST_01 1.0 [list source [file join $dir DEV_TEST_01.tc]]
package ifneeded RAID_HW_001 1.0 [list source [file join $dir RAID_HW_001.tc]]
package ifneeded RP_OUTLET_OFF 1.0 [list source [file join $dir RP_OUTLET_OFF.tc]]
package ifneeded SF_NRSP_HALT 1.0 [list source [file join $dir SF_NRSP_HALT.tc]]
package ifneeded SUB_TEST_001 1.0 [list source [file join $dir SUB_TEST_001.tc]]
package ifneeded TESTCASENAME 1.0 [list source [file join $dir TESTCASE_TEMPLATE.tp]]
