# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded PER_1000_SNORT 1.0 [list source [file join $dir PER_1000_SNORT.tc]]
package ifneeded PER_1000_SNORT_JUMBO 1.0 [list source [file join $dir PER_1000_SNORT_JUMBO.tc]]
package ifneeded PER_1000_SNORT_QOS 1.0 [list source [file join $dir PER_1000_SNORT_QOS.tc]]
package ifneeded PER_1000_ZBRIDGE 1.0 [list source [file join $dir PER_1000_ZBRIDGE.tc]]
package ifneeded PER_1000_ZBRIDGE_CPU 1.0 [list source [file join $dir PER_1000_ZBRIDGE_CPU.tc]]
package ifneeded PER_1000_ZBRIDGE_JUMBO 1.0 [list source [file join $dir PER_1000_ZBRIDGE_JUMBO.tc]]
package ifneeded PER_1000_ZBRIDGE_QOS 1.0 [list source [file join $dir PER_1000_ZBRIDGE_QOS.tc]]
package ifneeded PER_1000_ZBRIDGE_QOS_CPU 1.0 [list source [file join $dir PER_1000_ZBRIDGE_QOS_CPU.tc]]
package ifneeded PER_1000_ZBRIDGE_QOS_JUMBO 1.0 [list source [file join $dir PER_1000_ZBRIDGE_QOS_JUMBO.tc]]
package ifneeded PER_1000_ZBRIDGE_QOS_SOFTBYPASS 1.0 [list source [file join $dir PER_1000_ZBRIDGE_QOS_SOFTBYPASS.tc]]
package ifneeded PER_1000_ZBRIDGE_SOFTBYPASS 1.0 [list source [file join $dir PER_1000_ZBRIDGE_SOFTBYPASS.tc]]
