# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded APP_ARGUS 1.0 [list source [file join $dir APP_ARGUS.tc]]
package ifneeded APP_ARPWATCH 1.0 [list source [file join $dir APP_ARPWATCH.tc]]
package ifneeded APP_BARNYARD 1.0 [list source [file join $dir APP_BARNYARD.tc]]
package ifneeded APP_BARNYARD2 1.0 [list source [file join $dir APP_BARNYARD2.tc]]
package ifneeded APP_BRO 1.0 [list source [file join $dir APP_BRO.tc]]
package ifneeded APP_NPROBE 1.0 [list source [file join $dir APP_NPROBE.tc]]
package ifneeded APP_SANCP 1.0 [list source [file join $dir APP_SANCP.tc]]
package ifneeded APP_SILK 1.0 [list source [file join $dir APP_SILK.tc]]
package ifneeded APP_SNORT_283 1.0 [list source [file join $dir APP_SNORT_283.tc]]
package ifneeded APP_SNORT_285 1.0 [list source [file join $dir APP_SNORT_285.tc]]
package ifneeded APP_SNORT_291 1.0 [list source [file join $dir APP_SNORT_291.tc]]
package ifneeded APP_SQUID 1.0 [list source [file join $dir APP_SQUID.tc]]
package ifneeded APP_TCPDUMP 1.0 [list source [file join $dir APP_TCPDUMP.tc]]
package ifneeded APP_YAF 1.0 [list source [file join $dir APP_YAF.tc]]
package ifneeded APP_ZTCPDUMP 1.0 [list source [file join $dir APP_ZTCPDUMP.tc]]
