# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded XLR_LB_ETHER_1MPLSTAG 1.0 [list source [file join $dir XLR_LB_ETHER_1MPLSTAG.tc]]
package ifneeded XLR_LB_ETHER_2MPLSTAG 1.0 [list source [file join $dir XLR_LB_ETHER_2MPLSTAG.tc]]
package ifneeded XLR_LB_ETHER_3MPLSTAG 1.0 [list source [file join $dir XLR_LB_ETHER_3MPLSTAG.tc]]
package ifneeded XLR_LB_ETHER_4MPLSTAG 1.0 [list source [file join $dir XLR_LB_ETHER_4MPLSTAG.tc]]
package ifneeded XLR_LB_ETHER_5MPLSTAG 1.0 [list source [file join $dir XLR_LB_ETHER_5MPLSTAG.tc]]
