# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded NCCS_CLI_CONFIGURE 1.0 [list source [file join $dir NCCS_CLI_CONFIGURE.tc]]
package ifneeded NCCS_CLI_DEBUG 1.0 [list source [file join $dir NCCS_CLI_DEBUG.tc]]
package ifneeded NCCS_CLI_NO 1.0 [list source [file join $dir NCCS_CLI_NO.tc]]
package ifneeded NCCS_CLI_SHOW 1.0 [list source [file join $dir NCCS_CLI_SHOW.tc]]
package ifneeded NCCS_CLI_TOOLS 1.0 [list source [file join $dir NCCS_CLI_TOOLS.tc]]
package ifneeded NCCS_URL_ESOFT_DEFAULT_DROP 1.0 [list source [file join $dir NCCS_URL_ESOFT_DEFAULT_DROP.tc]]
package ifneeded NCCS_URL_ESOFT_DEFAULT_FORWARD 1.0 [list source [file join $dir NCCS_URL_ESOFT_DEFAULT_FORWARD.tc]]
package ifneeded NCCS_URL_ESOFT_DEFAULT_FORWARD_PC 1.0 [list source [file join $dir NCCS_URL_ESOFT_DEFAULT_FORWARD_PC.tc]]
package ifneeded NCCS_URL_ESOFT_DEFAULT_REDIRECT 1.0 [list source [file join $dir NCCS_URL_ESOFT_DEFAULT_REDIRECT.tc]]
package ifneeded NCCS_URL_ESOFT_DEFAULT_REJECT 1.0 [list source [file join $dir NCCS_URL_ESOFT_DEFAULT_REJECT.tc]]
package ifneeded NCCS_URL_ESOFT_OBLIGATORY_DROP 1.0 [list source [file join $dir NCCS_URL_ESOFT_OBLIGATORY_DROP.tc]]
package ifneeded NCCS_URL_ESOFT_OBLIGATORY_FORWARD 1.0 [list source [file join $dir NCCS_URL_ESOFT_OBLIGATORY_FORWARD.tc]]
package ifneeded NCCS_URL_ESOFT_OBLIGATORY_REDIRECT 1.0 [list source [file join $dir NCCS_URL_ESOFT_OBLIGATORY_REDIRECT.tc]]
package ifneeded NCCS_URL_ESOFT_OBLIGATORY_REJECT 1.0 [list source [file join $dir NCCS_URL_ESOFT_OBLIGATORY_REJECT.tc]]
